name: Snyk Static Analysis Scan
# This SAST (Static Application Security Testing) scan is used to scan
# our first-party code for security vulnerabilities
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - develop
jobs:
  Snyk_SAST_Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Perform Static Analysis Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        continue-on-error: true
        run: snyk code test  --strict-out-of-sync=false --detection-depth=6 --exclude=docker,Dockerfile --severity-threshold=high
